### ISSUE TITLE
 Vue.js devtools cannot display components normally after using the modified plugin

### ISSUE THREAD

**Issue by Striveeeee** [arktosk/vue-jss-plugin#40]
The effect is as follows：
![image](https://user-images.githubusercontent.com/26087376/122203469-a6175b00-ced0-11eb-8c5d-7343e6383447.png)
After I checked the source code, I found the reason is here:
![image](https://user-images.githubusercontent.com/26087376/122203772-f7bfe580-ced0-11eb-8d29-c13c15597060.png)
Why do you need to do this 🤔, I removed it and found that it can be used normally
Looking forward to your answer.

**Comment by arktosk** [comment]
Hey @Striveeeee, 
so it looks like some leftover, since there is no more usage of the component name, but the idea was to add component name to the style tags and class names in dev mode to have visibility of which styles belongs to what component.

However, it can be changed as plugin shouldn't modify the component options by itself as it can cause unexpexted side effects.

And I would like ask you also for a favor, can you share with me screenshot with your normal look of the components in devtools? I'm asking because something that is not usuall for you looks normally for me ;)

**Comment by arktosk** [comment]
@Striveeeee, please update the vue-jss-plugin dependency in your project to version **1.2.3**.

Please also send some feedback if now it works as expected, so then I will close the issue, thanks in advance!

**Comment by arktosk** [comment]
Closing the issue, due to the fix.
